### ISSUE TITLE
How to get client id and client secret 

### ISSUE THREAD

**Issue by neillturner** [pendrica/kitchen-azurerm#10]
I was able to follow along the instructions from 
  https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/#authenticate-service-principal-with-password---azure-cli
but no sure what client id and client secret is. 
I tried using the application id and the password as the client id and client secret but when i try a kitchen create i get error:
   {"error"=>{"code"=>"AuthorizationFailed", "message"=>"The client '38a99999-9999-9999-9999-b99999e3da5' with object id '38a99999-9999-9999-9999-b99999e3da5' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/a9999999-9999-9999-9999-999999999999/resourcegroups/kitchen-default-windows2012-r2-20151129T184927'."}}

**Comment by stuartpreston** [comment]
@neillturner Yes, it should be the application id and the password/secret set for the application. As you are using the azure-cli, have you tried logging in using the application id and password:

```
PS C:\Users\StuartPreston> azure login -u 02a2ba0d-YOUR-GUID-HERE-0e7cd312d62b -p "my-to
p-secret-password" --service-principal --tenant 9c117323-YOUR-GUID-HERE-9ee430723ba3
```

```
info:    Executing command login
/info:    Added subscription Microsoft Partner Network
+
info:    login command OK
```

**Comment by neillturner** [comment]
Ok im logging ok but i when it tries to create a resource group then i get an authorisation failure. maybe you have to be authorised somehow to use the azure resource manager. -)

**Comment by stuartpreston** [comment]
Did you miss the role assignment bit perhaps? This is where the objectID of your service principal (note not your application ID!) is given the specific right on the subscription.

Here's the command I used:

```
C:\Users\StuartPreston> azure role assignment create --objectId c49c3e61-YOUR-GUID-HERE-86c61ab2f428 -o Owner -c /subscriptions/b6e7eee9-YOUR-GUID0HERE-03ab624df016
info:    Executing command role assignment create
+ Finding role with specified name
data:    RoleAssignmentId     : /subscriptions/b6e7eee9-YOUR-GUID-HERE-03ab624df016/providers/Microsoft.Authorization/roleAssignments/53c94040-YOUR-GUID-HERE-cabe8abd6560
data:    RoleDefinitionName   : Owner
data:    RoleDefinitionId     : 8e3af657-YOUR-GUID-HERE-2fe8c4bcb635
data:    Scope                : /subscriptions/b6e7eee9-YOUR-GUID-HERE-03ab624df016
data:    Display Name         : automation-chef
data:    SignInName           :
data:    ObjectId             : c49c3e61-YOUR-GUID-HERE-86c61ab2f428
data:    ObjectType           : ServicePrincipal
```

Any use??

**Comment by neillturner** [comment]
Stuart, 
 thanks for your prompt reply I have it working.thanks for writing the plugin very useful. unfortunately I been spoiled these last 6 years with Amazon AWS excellent documentation.  
 when i used 
  azure role assignment create --objectId c49c3e61-YOUR-GUID-HERE-86c61ab2f428 -o Owner -c /subscriptions/b6e7eee9-YOUR-GUID0HERE-03ab624df016
instead of 
  azure role assignment create --objectId c49c3e61-YOUR-GUID-HERE-86c61ab2f428 -o Reader -c /subscriptions/b6e7eee9-YOUR-GUID0HERE-03ab624df016
which is what is in: 
https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/#authenticate-service-principal-with-password---azure-cli
It works. 
 So for others who find this after searching google. 
  use -Owner instead of -Reader
and when using kitchen-azurerm
use  application id as the client_id
and the password/secret as the client_secret

**Comment by stuartpreston** [comment]
@neillturner Glad you were able to get it working. I will take the above feedback and see what can be done with the project readme too.
