### ISSUE TITLE
Could not load the 'azurerm' driver from the load path

### ISSUE THREAD

**Issue by glennmate** [pendrica/kitchen-azurerm#15]
After upgrading to the latest Chef-DK (0.9.0->0.10.0):

```
PS C:\chef-starter\chef-repo\path-to-my-cookbook> kitchen create
-----> Starting Kitchen (v1.4.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'azurerm' driver from the load path. Please ensure that your driver is installed as a
 gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I've uninstalled and reinstalled the Chef-DK, including other versions. Seems broken now. Could this be a path issue? When using the vagrant driver I can kitchen create without issue. 

```chef gem install kitchen-azurerm``` appears to be working:

```
PS C:\chef-starter\chef-repo\cookbooks\path-to-cookbook> gem install kitchen-azurerm
Successfully installed concurrent-ruby-1.0.0
Successfully installed faraday-cookie_jar-0.0.6
Successfully installed timeliness-0.3.7
Successfully installed ms_rest-0.1.2
Successfully installed ms_rest_azure-0.1.2
Successfully installed azure_mgmt_network-0.1.1
Successfully installed azure_mgmt_resources-0.1.1
Successfully installed kitchen-azurerm-0.2.3
Parsing documentation for concurrent-ruby-1.0.0
Parsing documentation for faraday-cookie_jar-0.0.6
Parsing documentation for timeliness-0.3.7
Parsing documentation for ms_rest-0.1.2
Parsing documentation for ms_rest_azure-0.1.2
Parsing documentation for azure_mgmt_network-0.1.1
Parsing documentation for azure_mgmt_resources-0.1.1
Parsing documentation for kitchen-azurerm-0.2.3
Done installing documentation for concurrent-ruby, faraday-cookie_jar, timeliness, ms_rest, ms_rest_azure, azure_mgmt_ne
twork, azure_mgmt_resources, kitchen-azurerm after 7 seconds
8 gems installed
```

And to add,  ```Bundle show kitchen-azurerm``` yields the following output:
```
C:/Users/gmate/.chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.1
```

Though I do see a discrepency between the version installed with chef gem install (0.2.3) and the bundle show (0.2.1). Any ideas on how to get my test-kitchen working in Azure again? Help greatly appreciated. I didn't think upgrading ChefDK would cause any harm as I had no issues upgrading in the past.

**Comment by glennmate** [comment]
Interestingly enough, 'chef gem list kitchen-azurerm' yields no local gem results. kitchen-vagrant does, however. I have uninstalled and reinstalled kitchen-azurerm with no success. It claims to be installing but won't show under my local gems.

**Comment by stuartpreston** [comment]
That's interesting, will try this in my own environment tomorrow to see what's going on unless anyone else can comment.

**Comment by stuartpreston** [comment]
@glennmate Did you get any further with this. I tried in my own environment that I upgraded from 0.9.x to 0.10.0 and didn't have any problems.

What I see:

```
C:\Users\StuartPreston\kitchen-azurerm [master +0 ~2 -0]> chef gem list kitchen-azurerm

*** LOCAL GEMS ***

kitchen-azurerm (0.2.3)
```

Can you check your paths using ```chef gem env``` and also check that your ```$profile``` is correctly including ```chef shell-init powershell | iex```

**Comment by glennmate** [comment]
@stuartpreston Haven't had time to play with this just yet but I will and update this issue case; it could very well be a local issue. I'm going to try on another machine straight from 10.0 (not upgrading) and report back

**Comment by glennmate** [comment]
@stuartpreston  We're going to call this a local issue because I can't replicate anymore after making a few minor changes to my gem settings and reinstalling Chef DK - sorry for the false issue report but I appreciate the quick responses. .
