### ISSUE TITLE
SSL validation error on https://login.windows.net login attempt

### ISSUE THREAD

**Issue by Lees-Oz** [pendrica/kitchen-azurerm#17]
Hi!
I'm new to Ruby and not sure if that related to your project, so sorry if that's a wrong place.
I'm getting following error when converging the kitchen:
Creating Resource Group: kitchen-default-windows2012-r2-20160119T162913
```
 ------Exception-------
 Class: Kitchen::ActionFailed
 Message: Failed to complete #destroy action: [SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed]
```

After some debugging, found that it happens on attempt to retrieve auth token from https://login.windows.net.
Found a workaround for it, but it seem to be dirty:
`require 'openssl'`
`OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

Stacktrace:
```
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: Message: Failed to complete #create action: [SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed]
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: ---Nested Exception---
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: Class: Faraday::SSLError
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: Message: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: ------Backtrace-------
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `connect'
E, [2016-01-20T08:30:55.039677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `connect'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:852:in `start'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:1369:in `request'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
E, [2016-01-20T08:30:55.040677 #15828] ERROR -- Kitchen: C:/tools/ruby215/lib/ruby/gems/2.1.0/gems/ms_rest_azure-0.1.2/lib/ms_rest_azure/credentials/application_token_provider.rb:103:in `acquire_token' 
```

**Comment by stuartpreston** [comment]
This is strange as login.windows.net reports as a valid certificate at online certificate checking sites such as: https://cryptoreport.websecurity.symantec.com/checker/ 

We don't expect to have to override the SSL checking for Azure, so I would ask if it's possible there's a local proxy that may be causing the issue? Have you tried this on multiple connections?

**Comment by Lees-Oz** [comment]
Strange indeed. No, there's no proxy involved. Sorry, what do you mean with trying on multiple connections?

**Comment by stuartpreston** [comment]
Hmm, I've tried this in the UK and US and don't seem to have the same issue. What country are you in? Australia by any chance (or is your username just a coincidence?) I'm wondering if a CDN is redirecting you to a page with a misconfigured SSL. Yes it was home and office connections I meant.

**Comment by Lees-Oz** [comment]
I'm in Netherlands.

**Comment by stuartpreston** [comment]
This is strange then as I should be able to repro this easily. If you visit https://login.windows.net in a browser do you get the same warning when looking at the certificate?

**Comment by Lees-Oz** [comment]
Thanks for investigating it, Stuart!
Nop, browser reports that certificate for that site is fine, and I can login there.

**Comment by Lees-Oz** [comment]
Colleague of mine didn't have that problem, looks like that the problem is on my machine somehow.

**Comment by stuartpreston** [comment]
Let me know if you discover anything relating to the plugin and we can re-open the issue. I guess as a first stop I'd be looking at using OpenSSL on your machine to see if you have the correct root certificates, etc. Good luck!
