### ISSUE TITLE
Is Owner right required?

### ISSUE THREAD

**Issue by mhedgpeth** [pendrica/kitchen-azurerm#20]
I went through the directions and am using azure for the first time, so the security setup was difficult for me. I'm thinking of sending a pull request that explains that part a bit better for new people. Before I do that, could you confirm that Owner rights are needed? I used contributor (because I didn't carefully read your documentation) and it seems to work well.

**Comment by stuartpreston** [comment]
Hi @mhedgpeth - a PR would be great, I had a look into it and yes it looks like Owner rights are not explicitly needed at the subscription level as typically the creator of the resources in Azure doesn't need access to other resources in the subscription.

**Comment by mhedgpeth** [comment]
I sent a PR on the updated documentation; the contributor works best for me. Thanks!
