### ISSUE TITLE
Question: will this work with P2P encryption?

### ISSUE THREAD

**Issue by mhedgpeth** [pendrica/kitchen-azurerm#23]
This is more of a question than an issue: I'm having trouble with corporate LAN rules that prevent me from using winrm properly to azure. I want to create a P2P connection (https://azure.microsoft.com/en-us/documentation/articles/vpn-gateway-point-to-site-create/). If I have that connection set up would test kitchen using this driver create resources _within_ that connection?

**Comment by stuartpreston** [comment]
I don't believe so. The driver will always use the public IP allocated. In a P2P connection I believe that traffic goes via the existing Internet route. We could consider adding a 'use_internal_ip' option for this which should be easy to implement...

**Comment by mhedgpeth** [comment]
OK thanks, I'll test it if I need to go that route & see if I can create a PR with it (no promises at the moment, though; I'm new to azure)

**Comment by stuartpreston** [comment]
I'm going to close this for now, in favour of something I'm adding soon that will let you use a secondary ARM deployment prior to testing with InSpec.  This will open up (e.g.) testing of PaaS resources with testing coordinated through a single node (and can also be used for any custom connectivity or environment requirements you may have too).  Hope that's ok.
