### ISSUE TITLE
Can't run Kitchen Converge Windows 2012

### ISSUE THREAD

**Issue by MELLENS** [pendrica/kitchen-azurerm#26]
I'm not able to run Kitchen Converge - any suggestions?.  I get Exception:

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "xx.xxx.xxx.xxx" port 5985 
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

There's no NSGs in place in Azure - I seem to be able to RDP to the box but don't know where to look for the username and password so can't investigate further.  

I've tried recreating this in Kitchen and got the same error both times.

.kitchen.yml:

---
driver:
  name: azurerm

driver_config:
  subscription_id: 'MY-GUID'
  location: 'North Europe'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero_scheduled_task

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
      winrm_powershell_script: |-
        winrm quickconfig -q
        winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
        winrm set winrm/config '@{MaxTimeoutms="1800000"}'
        winrm set winrm/config/service '@{AllowUnencrypted="true"}'
        winrm set winrm/config/service/auth '@{Basic="true"}'
    transport:
      name: winrm

suites:
  - name: default
    run_list:
       recipe[kitchentesting::default]

**Comment by stuartpreston** [comment]
Windows 2012 R2 should not need the winrm_powershell_script in order to configure itself so you could try taking that out in case your script is wrong. 

The username and password are ```.\azure``` and ```P2ssw0rd``` respectively if unset (this info is in the readme).  The public IP is directly bound to a NIC directly attached to the VM so there shouldn't be any NSG rules in place.

**Comment by stuartpreston** [comment]
Is it also possible you are being a firewall blocking public access to port TCP/5985?

**Comment by MELLENS** [comment]
Was the powershell I copied from the ec2 demo kitchen config I think.  Pulling that out worked well.  I'll try and RTFM a few more times before asking for user names etc.  Closing this.
