### ISSUE TITLE
Security Group

### ISSUE THREAD

**Issue by msghaleb** [pendrica/kitchen-azurerm#28]
Hi Guys,

thanks for the great work!

how about the security group? I use Test Kitchen to trigger ansible and test few things on the box, however without the correct ports opened its not possible.

How to you deal with this part?

Regards,

MG

**Comment by stuartpreston** [comment]
Hi there. The public IP is directly bound to the NIC. There are no NSG in force here. So any port open on the created node is available to the public internet. Beware of this but hope it helps!

**Comment by msghaleb** [comment]
Thank you!

**Comment by pkazi** [comment]
We can attach a NSG to the subnet where Kitchen Azure VM is going to be created -
Read more in - https://social.msdn.microsoft.com/Forums/azure/en-US/da12fe95-683a-4ad8-9504-13444cc76afd/azure-kitchen-network-security-group?forum=WAVirtualMachinesVirtualNetwork
This NSG will be applicable to all the VMs launched in that subnet.
