### ISSUE TITLE
Kitchen create: Failed to complete #create action: [undefined method `[]' for nil:NilClass]

### ISSUE THREAD

**Issue by glennmate** [pendrica/kitchen-azurerm#3]
First off, my apologies if the syntax or formatting here is absolutely backwards. I am new to Github. Basically I am working with a certified Chef consultant in attempts to get our infrastructure connected to Azure. I have connected my information to Azure successfully but fail out when attempting to Kitchen Create. Workstation is Windows 7, any assistance is appreciated. The main error is:

Failed to complete #create action: [undefined method `[]' for nil:NilClass]

And the kitchen.log files point to azurerm.rb. I've copied the information here for you to review. 

PS C:\chef-starter\chef-repo\cookbooks\na-iis> kitchen create
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-windows2012-r2>...
       Creating Resource Group: kitchen-default-windows2012-r2-20151006T194753
 ------Exception-------
Class: Kitchen::ActionFailed
Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
----------------------
Please see .kitchen/logs/kitchen.log for more details
Also try running `kitchen diagnose --all` for configuration

Kitchen.log file:

I, [2015-10-06T15:47:48.681628 #5996]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
I, [2015-10-06T15:47:53.481107 #5996]  INFO -- Kitchen: -----> Creating <default-windows2012-r2>...
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: ------Exception-------
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: ---Nested Exception---
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: Class: NoMethodError
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: Message: undefined method `[]' for nil:NilClass
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: ------Backtrace-------
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.1/lib/kitchen/driver/azurerm.rb:65:in `rescue in create'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.1/lib/kitchen/driver/azurerm.rb:61:in `create'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:127:in `create'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/Users/gmate/AppData/Local/chefdk/gem/ruby/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2015-10-06T15:47:53.995894 #5996] ERROR -- Kitchen: ----------------------

Contents of my kitchen YML for the cookbook:

---
driver:
  name: azurerm

driver_config:
  subscription_id: "a7c8aa2c-8e9d-410a-8b84-0464b4d7e8eb"
  location: "East US"
  machine_size: "Standard_A3"

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[na-iis::default]
    attributes:

Gems:
PS C:\chef-starter\chef-repo\cookbooks\na-iis> gem list | grep kitchen
kitchen-azure (0.1.0)
kitchen-azurerm (0.2.1)
kitchen-nodes (0.4.1)
kitchen-vagrant (0.19.0)
test-kitchen (1.4.2

Output of Chef -v:
Chef Development Kit Version: 0.8.1
chef-client version: 12.4.4
berks version: 3.3.0
kitchen version: 1.4.2

EDIT: I just rebuilt my system in a VM and got the same error on a server 2012 R2 machine. Others going through this task have an earlier version of Chef DK and were able to complete without issue it seems.

**Comment by stuartpreston** [comment]
Failing at that point generally points to an issue with your credentials file. I'm updating my Windows system to check 0.8.1 of ChefDK doesn't exhibit the same behaviour.

Can you triple check your ~/.azure/credentials file - make sure it is UTF-8 encoded and the first line starts ```[a7c8aa2c-8e9d-410a-8b84-0464b4d7e8eb]```

Which is your Subscription ID.  There should be 3 lines after that:

```
client_id = "<service principal object id>"
client_secret = "<service principal secret>"
tenant_id = "<azure tenant id>"
```

I'm going to install ChefDK 0.8.1 to make sure everything is working on my system.

**Comment by glennmate** [comment]
It was the UTF-8 encoding. I recreated the credentials file word-for-word in another text editor and the problem did not present itself. You can close this issue. Thanks for the point in the right direction.

**Comment by stuartpreston** [comment]
@glennmate Glad to hear it is working!
