### ISSUE TITLE
Driver should validate that transport can connect before successfully completing.

### ISSUE THREAD

**Issue by smurawski** [pendrica/kitchen-azurerm#30]
Several other drivers include

```
instance.transport.connection(@state).wait_until_ready
```

in their create method to validate that ktichen can, in fact, connect to those instances before returning successfully.  I've hit a few failed converges due to the script extension not completing properly (but not erroring) and have failed to connect as kitchen transitioned into the converge phase.

**Comment by stuartpreston** [comment]
Hmm. Sounds like something we should be using,.. Saying that, if the script extension doesn't complete properly we want to fail as quickly as possible, so would adding a wait_until_ready add anything here?

**Comment by stuartpreston** [comment]
I had a look at this for the latest build but decided to go with my own option to fail faster rather than make people wait.  If you strongly believe otherwise let's chat :)

**Comment by smurawski** [comment]
Sorry I didn't get back to you sooner.  What the `wait_until_ready` does is validate that winrm (or whatever transport) can actually connect to the provisioned instance.  It doesn't add much overhead, but makes sure the move from create to converge will be able to proceed.  It's not a huge deal to me, but I'm not using it a lot at the moment (working on a different project currently).

**Comment by stuartpreston** [comment]
I can tell ;-)
I'm making a bunch of changes in that area so will look at incorporating it into the next build :-)
