### ISSUE TITLE
Connect on private ip?

### ISSUE THREAD

**Issue by dpnl87** [pendrica/kitchen-azurerm#31]
Is it possible to connect on the private ip instead of the public one? We have a ExpressRoute in place. This is on a BGP level which as an by effect blocks our traffic to the public ip addresses.

**Comment by stuartpreston** [comment]
Not currently but I think if I gave you the ability to specify a VLAN and an attribute in the kitchen.yml to connect to the private IP that would be all you need?  I'll try and have a look in the coming week if you can help test with your ExpressRoute?

**Comment by dpnl87** [comment]
Thank you @stuartpreston that would be awesome! 👍

**Comment by stuartpreston** [comment]
Hi @dpnl87 - please update your kitchen-azurerm (any version from 0.5.0) and give this a try.  You can now specify a ```vlan_id``` and ```subnet_id``` - [example config](https://github.com/pendrica/kitchen-azurerm#kitchenyml-example-4---deploy-vm-to-existing-virtual-networksubnet-use-for-expressroutevpn-scenarios)

**Comment by stuartpreston** [comment]
Hi @dpnl87 I left this open for a couple of weeks but guess you haven't been able to try yet.  I will close this thread for now, please open a new issue if you have problems getting it working...

**Comment by dpnl87** [comment]
I completely missed your first ping @stuartpreston :(. I've tested with 2 different subscriptions and both work fine now! Thnx for the effort! 👍
