### ISSUE TITLE
problem when installing via chef on ubuntu 14

### ISSUE THREAD

**Issue by moshezvi** [pendrica/kitchen-azurerm#33]
When trying to install the gem in chef (using chef_gem) I get the following error:
```
---- Begin output of /opt/chef/embedded/bin/gem install kitchen-azurerm -q --no-rdoc --no-ri -v "0.5.0" ----
       STDOUT:
       STDERR: ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
           ms_rest_azure-0.3.1 requires ms_rest (~> 0.3.0) but it conflicted:
         Activated ms_rest-0.3.1 instead of (= 0.1.2) via:
           kitchen-azurerm-0.5.0
       ---- End output of /opt/chef/embedded/bin/gem install kitchen-azurerm -q --no-rdoc --no-ri -v "0.5.0" ----
```

Seems like 0.5.0 still uses the old ms_rest (0.1.2), and this conflicts with newer requirements for ms_rest_azure.
gem version: 2.1.11

**Comment by stuartpreston** [comment]
@moshezvi Thanks for the report, I will try and repro - what version of ChefDK were you running?  I am going to try and push an updated version that uses the latest ms_rest bits and avoids the hard dependency.

**Comment by stuartpreston** [comment]
I just upgraded all the dependencies to use the latest dependencies.  Hopefully I have picked a dependency high enough up the chain to avoid this problem in future.  Any build from 0.6.0 upwards on RubyGems has this fix in.  I will close this for now, please open a new ticket if you continue to have dependency problems.
