### ISSUE TITLE
SSL validation error while running kitchen converge

### ISSUE THREAD

**Issue by vikrant-wagh** [pendrica/kitchen-azurerm#34]
I am trying to run kitchen converge on a Windows Server 2012 R2 machine, I am getting following error
Failed to complete #create action: [SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed] on default-windows2012-r2

kitchen diagnose runs fine. I also checked the details in ~/.azure/credentials file. I think they are valid.

[kitchen-converge-log.txt](https://github.com/pendrica/kitchen-azurerm/files/464498/kitchen-converge-log.txt)
[kitchen-diagnose-log.txt](https://github.com/pendrica/kitchen-azurerm/files/464497/kitchen-diagnose-log.txt)
[kitchen.yml.txt](https://github.com/pendrica/kitchen-azurerm/files/464502/kitchen.yml.txt)

**Comment by stuartpreston** [comment]
Please can you remove the winrm_powershell_script configuration and retry?

Failing that you may need to revert to a previous version of Test Kitchen (<1.12) - the latest version pulls in the latest winrm gem which I can not yet tested.




On Fri, Sep 9, 2016 at 6:46 PM +0100, "vikrant-wagh" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to run kitchen converge on a Windows Server 2012 R2 machine, I am getting following error
Failed to complete #create action: [SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed] on default-windows2012-r2

kitchen diagnose runs fine. I also checked the details in ~/.azure/credentials file. I think they are valid.

kitchen-converge-log.txt<https://github.com/pendrica/kitchen-azurerm/files/464498/kitchen-converge-log.txt>
kitchen-diagnose-log.txt<https://github.com/pendrica/kitchen-azurerm/files/464497/kitchen-diagnose-log.txt>

-

**Comment by vikrant-wagh** [comment]
First I didn't have the PowerShell winrm script but I was getting same error. I added that script to see if it works with overriden winrm settings. 

I will revert kitchen-azurerm version and try.

Thanks a lot for the prompt response.

**Comment by vikrant-wagh** [comment]
I reverted the version, still I am facing same issue. I am attaching the log and my Gemfile.

[kitchen-converge-log-20161112.txt](https://github.com/pendrica/kitchen-azurerm/files/466720/kitchen-converge-log-20161112.txt)

**Comment by stuartpreston** [comment]
Looking at the converge it's failing to connect the management API.  This is controlled by the following URL that should be visible by doing a ```kitchen diagnose --all``

```
    driver:
      azure_management_url: https://management.azure.com
```

Can you use your local browser to connect to https://management.azure.com to see if there are issues?

**Comment by vikrant-wagh** [comment]
I think this issue is because of my office firewall. Working fine with my home network. I am able to work with test-kitchen-1.12.0.

**Comment by stuartpreston** [comment]
That's good, I was also going to report that I've tested the driver with test kitchen 1.12 and it seems ok.  You may be able to adjust your HTTP_PROXY settings in the office. 

I shall close this issue for now.  Please open a new issue if you continue to encounter problems.
