### ISSUE TITLE
Access to pre_deployment_template outputs

### ISSUE THREAD

**Issue by nexus49** [pendrica/kitchen-azurerm#35]
I did not see this being mentioned in the docs, but is there a way to access output values from the pre_deployment template?

What i am trying to achieve is to create a storageaccount in the template and then make use of the storage key in the recipe. Would you have a recommendation on how to do that?

**Comment by stuartpreston** [comment]
There is not a way to do that currently I'm afraid, output values from the ARM template are disregarded.  One option may be to make the output values available to your recipe via environment variables somehow, would that suit your scenario?

**Comment by nexus49** [comment]
Hm, not sure i understand how to achieve that. Lets assume i have a template that creates a storage account, similar how you create the SQL server in the example 3. 

How would i hook into the test instance creation from kitchen to provide additional environment variables that would contain the storage key?

**Comment by stuartpreston** [comment]
Sorry, I was discussing a possible future enhancement to achieve this - it is not possible today and would require some development on the driver (and possibly in core to allow reloading of the configuration mid-way through a command).

**Comment by nexus49** [comment]
Ah I see - well i think it may be a common use case that a recipe has certain attributes that it uses, that cannot be statically provided during a kitchen test - the storage key is a good example for that. 

One solution that would work, if those template outputs are loaded in the node attributes - this would allow me to add another recipe in the test suite to set the attributes to where i need them. I'm not super experienced on the matter, so there are possibly better ways :-)

**Comment by nexus49** [comment]
Ok i solved it for now, to setup that needed storage account on a different resource group manually. That way i can just configure the key in kitchen as an attribute. Downside to this is that this storageaccount is always existing and not destroyed/created for a recipe on test.

**Comment by stuartpreston** [comment]
I'm going to close this for now as you have a workaround but I've noted the requirement in case I see an easy way to accomplish this later.
