### ISSUE TITLE
"Couldn't login to Azure, please verify your tenant id, client id and client secret"

### ISSUE THREAD

**Issue by anniehedgpeth** [pendrica/kitchen-azurerm#36]
Hi Stuart! 

I followed your directions to set up a credentials file with the subscription id, client id, client secret, and tenant id, however I keep getting this error when I try to run `kitchen create` like it can't find my credentials:

`"Couldn't login to Azure, please verify your tenant id, client id and client secret"`  

Could it be an issue that I'm on a Mac? 

Thanks!

**Comment by stuartpreston** [comment]
Hi Annie! That's strange. It's usually one of the following things:

- credentials file needs to be saved in ~/.azure/credentials in UTF8 format (use Visual Studio Code to verify and switch encoding if not)
- Subscription ID needs to be surrounded with square brackets [ ] on the first line of the file. 
- Service Principal is not created correctly in Azure (check you can login using the azure login --service-principal command (and a whole bunch of other command line switches). 

If none of that works please could you email me the output of kitchen create -l debug to stuart@pendrica.com with a sample of your credentials file and I will try it on my Mac again!

**Comment by stuartpreston** [comment]
Closing as resolved offline.
