### ISSUE TITLE
Failed to complete #create action

### ISSUE THREAD

**Issue by phillipbroberts** [pendrica/kitchen-azurerm#4]
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-centos-71>
-----> Destroying <default-centos-71>...
       Finished destroying <default-centos-71> (0m0.00s).
-----> Testing <default-centos-71>
-----> Creating <default-centos-71>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by phillipbroberts** [comment]
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-centos-71>
-----> Destroying <default-centos-71>...
       Finished destroying <default-centos-71> (0m0.00s).
-----> Testing <default-centos-71>
-----> Creating <default-centos-71>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by phillipbroberts** [comment]
I, [2015-10-20T17:39:19.488941 #12532]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
I, [2015-10-20T17:39:25.697169 #12532]  INFO -- Kitchen: -----> Cleaning up any prior instances of <default-centos-711>
I, [2015-10-20T17:39:25.698179 #12532]  INFO -- Kitchen: -----> Destroying <default-centos-711>...
I, [2015-10-20T17:39:25.701174 #12532]  INFO -- Kitchen: -----> Testing <default-centos-711>
I, [2015-10-20T17:39:25.702173 #12532]  INFO -- Kitchen: -----> Creating <default-centos-711>...
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: ------Exception-------
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: Message: Failed to complete #create action: [undefined method `[]' for nil:NilClass]
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: ---Nested Exception---
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: Class: NoMethodError
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: Message: undefined method `[]' for nil:NilClass
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: ------Backtrace-------
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: C:/Users/Phillip/chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.1/lib/kitchen/driver/credentials.rb:30:in `azure_credentials_for_subscription'
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: C:/Users/Phillip/chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.1/lib/kitchen/driver/azurerm.rb:54:in `create'
E, [2015-10-20T17:39:25.708177 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `call'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:160:in `verify'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:185:in `test'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: C:/opscode/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-10-20T17:39:25.709180 #12532] ERROR -- Kitchen: ----------------------

**Comment by phillipbroberts** [comment]
I am checking my credentials file. Will let you know if this fixes it.

**Comment by phillipbroberts** [comment]
I used Sublime Text 3 to recreate my credentials file line for line and saved as UTF-8 and it did not fix the issue :(

**Comment by phillipbroberts** [comment]
I also verified the data used in the credentials file with azure login.

**Comment by stuartpreston** [comment]
This looks curious as no instances are listed to be created as far as I can see... Can you post the output of kitchen list/kitchen diagnose and if you want me to have a deeper look send me your files to the address listed on my GitHub profile?

**Comment by phillipbroberts** [comment]
Its interesting because on a subsequent run, it fails with same error however, it fails to destory.

PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-centos-711>
-----> Destroying <default-centos-711>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [undefined method `[]' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Requested information is on its way.

**Comment by phillipbroberts** [comment]
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen list
Instance            Driver   Provisioner  Verifier  Transport  Last Action
default-centos-711  Azurerm  ChefZero     Busser    Ssh        <Not Created>

PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen diagnose --all
---
timestamp: 2015-10-21 13:26:54 UTC
kitchen_version: 1.4.2
plugins:
  driver:
    Azurerm:
      class: Kitchen::Driver::Azurerm
      version:
      api_version:
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.4.2
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.4.2
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.4.2
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/.kitchen.yml
    raw_data:
      driver:
        name: azurerm
      drive_config:
        subscription_id: d71449f9-4664-4005-9318-9d9a798f809c
        location: US East
        machine_size: Standard_D1
      provisioner:
        name: chef_zero
        require_chef_omnibus: 12.3.0
      platforms:
      - name: centos-7.1.1
        driver_config:
          image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      suites:
      - name: default
        run_list:
        - recipe[atlassian::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: azurerm
      drive_config:
        subscription_id: d71449f9-4664-4005-9318-9d9a798f809c
        location: US East
        machine_size: Standard_D1
      provisioner:
        name: chef_zero
        require_chef_omnibus: 12.3.0
      platforms:
      - name: centos-7.1.1
        driver_config:
          image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      suites:
      - name: default
        run_list:
        - recipe[atlassian::default]
        attributes:
instances:
  default-centos-711:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      azure_resource_group_name: kitchen-default-centos-711-20151020T213925
      password: P2ssw0rd
      server_id: vmdf4e97f8a7b7de27
      subscription_id:
      username: azure
      uuid: df4e97f8a7b7de27
    driver:
      azure_resource_group_name: kitchen-default-centos-711
      image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_level: :info
      name: azurerm
      password: P2ssw0rd
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      username: azure
    provisioner:
      attributes: {}
      chef_client_path: "/opt/chef/bin/chef-client"
      chef_metadata_url:
      chef_omnibus_install_options:
      chef_omnibus_root: "/opt/chef"
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,provid
ers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      require_chef_omnibus: 12.3.0
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/opt/chef/embedded/bin"
      run_list:
      - recipe[atlassian::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
    transport:
      compression: true
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      version: busser

**Comment by phillipbroberts** [comment]
Which files are you interested in?

**Comment by stuartpreston** [comment]
I may not need it... looking at your diagnose output... can you search for ```drive_config``` and replace with ```driver_config```?

**Comment by phillipbroberts** [comment]
Let me give it a shot. Nice catch.

**Comment by phillipbroberts** [comment]
I was going to be embarrassed if that was the issue, unfortunately, no joy. 

PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-centos-711>
-----> Destroying <default-centos-711>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [undefined method `[]' for nil:NilClass]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen list
Instance            Driver   Provisioner  Verifier  Transport  Last Action
default-centos-711  Azurerm  ChefZero     Busser    Ssh        <Not Created>
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> kitchen diagnose --all
---
timestamp: 2015-10-21 13:43:27 UTC
kitchen_version: 1.4.2
plugins:
  driver:
    Azurerm:
      class: Kitchen::Driver::Azurerm
      version:
      api_version:
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.4.2
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.4.2
      api_version: 1
  verifier:
    Busser:
      class: Kitchen::Verifier::Busser
      version: 1.4.2
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/.kitchen.yml
    raw_data:
      driver:
        name: azurerm
      driver_config:
        subscription_id: d71449f9-4664-4005-9318-9d9a798f809c
        location: US East
        machine_size: Standard_D1
      provisioner:
        name: chef_zero
        require_chef_omnibus: 12.3.0
      platforms:
      - name: centos-7.1.1
        driver_config:
          image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      suites:
      - name: default
        run_list:
        - recipe[atlassian::default]
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: azurerm
      driver_config:
        subscription_id: d71449f9-4664-4005-9318-9d9a798f809c
        location: US East
        machine_size: Standard_D1
      provisioner:
        name: chef_zero
        require_chef_omnibus: 12.3.0
      platforms:
      - name: centos-7.1.1
        driver_config:
          image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      suites:
      - name: default
        run_list:
        - recipe[atlassian::default]
        attributes:
instances:
  default-centos-711:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      azure_resource_group_name: kitchen-default-centos-711-20151020T213925
      password: P2ssw0rd
      server_id: vmdf4e97f8a7b7de27
      subscription_id:
      username: azure
      uuid: df4e97f8a7b7de27
    driver:
      azure_resource_group_name: kitchen-default-centos-711
      image_urn: OpenLogic:CentOS:7.1:7.1.20150731
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      location: US East
      log_level: :info
      machine_size: Standard_D1
      name: azurerm
      password: P2ssw0rd
      subscription_id: d71449f9-4664-4005-9318-9d9a798f809c
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      username: azure
    provisioner:
      attributes: {}
      chef_client_path: "/opt/chef/bin/chef-client"
      chef_metadata_url:
      chef_omnibus_install_options:
      chef_omnibus_root: "/opt/chef"
      chef_omnibus_url: https://www.chef.io/chef/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,provi
ers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      encrypted_data_bag_secret_key_path:
      environments_path:
      http_proxy:
      https_proxy:
      json_attributes: true
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_file:
      log_level: :info
      name: chef_zero
      nodes_path:
      require_chef_omnibus: 12.3.0
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/opt/chef/embedded/bin"
      run_list:
      - recipe[atlassian::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
    transport:
      compression: true
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      username: root
    verifier:
      busser_bin: "/tmp/verifier/bin/busser"
      http_proxy:
      https_proxy:
      kitchen_root: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian
      log_level: :info
      name: busser
      root_path: "/tmp/verifier"
      ruby_bindir: "/opt/chef/embedded/bin"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Users/Phillip/RubyMineProjects/atlassian/atlassian/cookbooks/atlassian/test/integration
      version: busser
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian>

**Comment by stuartpreston** [comment]
The next thing I spotted was the 'US East' is not a valid location - it's 'East US' - but testing locally I see you aren't getting that far.  Can you drop me your .kitchen.yml and a screenshot of your credentials file (feel free to blur out the service principal secret, etc.)

**Comment by stuartpreston** [comment]
The error from your first message does seem to point at an inability to get the tenant_id from the inifile (credentials).  I take it you have triple checked the first line is 

```
[d71449f9-4664-4005-9318-9d9a798f809c]
client_id = "<service principal id - NOTE NOT THE OBJECT ID>"
client_secret = "<service principal secret>"
tenant_id = "your-tenant-guid"
```

If you have the azure-cli installed, you can use ```azure ad sp list``` in ARM mode to verify the guid for the client_id, and azure account list to see the tenant_id

```
data:    Object Id:               984c5629-ABCD-EFAB-CDEF-a0d4a86037c2
data:    Display Name:            chef-provisioning
data:    Service Principal Names:
data:                             https://manage.chef.io
data:                             48b9bba3-YOUR-GUID-HERE-90f0b68ce8ba
```

Sorry if I'm going over stuff that is obvious.

**Comment by phillipbroberts** [comment]
Let me check that, and no, I am new to the azure stuff altogether, so there has definitely been some confusion in the GUID's and what not.

**Comment by phillipbroberts** [comment]
I think this might be were my confusion is: 

azure ad sp list : 
...
data:
data:    Object Id:               f2663a30-983c-4507-a4b1-bd0d5ea2596e
data:    Display Name:            Test Kitchen
data:    Service Principal Names:
data:                             https://ingenium-group.com
data:                             0aa9b952-913f-49a0-851e-f45cd76869dd
data:

azure account list: 
C:\WINDOWS\system32>azure account list
info:    Executing command account list
data:    Name           Id                                    Current  State
data:    -------------  ------------------------------------  -------  -------
data:    Pay-As-You-Go  d71449f9-4664-4005-9318-9d9a798f809c  true     Enabled
info:    account list command OK

This is my credentials file: 

[d71449f9-4664-4005-9318-9d9a798f809c]
client_id = "0aa9b952-913f-49a0-851e-f45cd76869dd"
client_secret = "my secret here"
tenant_id = "0b510259-ce1b-48d8-bdff-04c18b6983e1"

**Comment by stuartpreston** [comment]
It looks mostly OK based on what you've provided so far. I don't know why you don't see the tenant_id when doing an azure account list.  Are you logging on with a Microsoft Organizational/Work ID or a Microsoft Account/Live ID?  Did you verify your tenant_id in a portal?

**Comment by phillipbroberts** [comment]
Microsoft Organizational/Work ID - I did find the tenant_id somewhere, I want to say in the portal, but to be honest, I don't remember where, let me see if I can find it in the portal.

**Comment by phillipbroberts** [comment]
PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> Add-AzureAccount

Id                             Type       Subscriptions                                    Tenants
--                             ----       -------------                                    -------
phil@ingenium-group.com        User       d71449f9-4664-4005-9318-9d9a798f809c             0b510259-ce1b-48d8-bdff-04c18b6983e1


PS C:\Users\Phillip\RubyMineProjects\atlassian\atlassian\cookbooks\atlassian> Get-AzureAccount

Id                             Type       Subscriptions                                    Tenants
--                             ----       -------------                                    -------
0C9449B869AB696960D1CE8BA42142 Certificat d71449f9-4664-4005-9318-9d9a798f809c
8130B01552                     e
phil@ingenium-group.com        User       d71449f9-4664-4005-9318-9d9a798f809c             0b510259-ce1b-48d8-bdff-04c18b6983e1

**Comment by stuartpreston** [comment]
Ok, well all your guids would seem to be correct, so can I just confirm what's the latest error you get doing a kitchen create?  Did you find my direct email address?

**Comment by phillipbroberts** [comment]
Seems I have gotten it working. I am not sure how yet. I did remove a trailing line in the credentials file? I could see the possibly causing an issue?

**Comment by phillipbroberts** [comment]
Thanks for your attention and help man! The trailing line *MUST* have been the issue.
