### ISSUE TITLE
PowerShell Environment issue with ~

### ISSUE THREAD

**Issue by RamblingCookieMonster** [pendrica/kitchen-azurerm#40]
Hi!

Some code I'm using calls `~`.  I get the following error on initial converge:

```
Home location for this provider is not set. To set the home location, call "(get-psprovider 'FileSystem').Home = 'path'".
At line:14 char:29
$$$$$$ +     $NugetPath = Join-Path (Resolve-Path -Path ~).Path nuget.exe
```

This only happens on initial run.  If I run converge a second time, it resolves correctly.

I'd prefer to use `~` given that it should work across platforms, but, will change to `$ENV:UserProfile` for now (that variable does exist)

Cheers!

**Comment by stuartpreston** [comment]
I'm closing this issue for now - none of the WinRM code is in this project.  If it becomes a real issue for you I'd recommend raising in the https://github.com/test-kitchen/test-kitchen project.  Thanks.
